In [5]:
import pandas as pd
# On recharge le fichier CSV généré à l'étape précédente
df = pd.read_csv("churn_data.csv")
df.head()

   age  salaire abonnement  anciennete  consommation  churn
0   56     4543    Premium          12            77      0
1   69     6508    Premium           0            83      0
2   46     5270   Standard           9            21      0
3   32     5999    Premium           4            74      0
4   60     2670    Premium          11            26      0

In [6]:
df.shape

(500, 6)

In [7]:
df.describe()

              age     salaire  anciennete  consommation       churn
count  500.000000   500.00000  500.000000    500.000000  500.000000
mean    44.220000  4666.30800    7.144000     48.660000    0.038000
std     15.036082  1844.86557    4.364558     28.927115    0.191388
min     18.000000  1209.00000    0.000000      0.000000    0.000000
25%     32.000000  3124.75000    3.000000     23.750000    0.000000
50%     45.000000  4679.00000    7.000000     47.000000    0.000000
75%     57.000000  6225.25000   11.000000     74.250000    0.000000
max     69.000000  7988.00000   14.000000     99.000000    1.000000

In [8]:
df.isnull().sum()

age             0
salaire         0
abonnement      0
anciennete      0
consommation    0
churn           0
dtype: int64

In [9]:
df["churn"].value_counts()

churn
0    481
1     19
Name: count, dtype: int64